services:
  postgres:
    image: postgres:14.11
    container_name: postgres14.11
    environment:
      POSTGRES_USER: artur
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app_financas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
